name = "full"

[network]
wellknown = "Preview"

[ogmios]
enabled = true

[node]
enabled = true

[carp]
enabled = true

[proxy]
enabled = true
blockfrost_network = "cardano-preview"
blockfrost_api_key = "previewXXXXXSSSDSDS"
token_registry_url = "https://tokens.cardano.org"
